config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'films#index'
  resource :films, only: [:index]

  get 'evaluations' => 'evaluations#index', as: :list_evaluations
  post 'evaluations/:film_api_id/:evaluation' => 'evaluations#create', as: :create_evaluations
  delete 'evaluations/:evaluation_id' => 'evaluations#destroy', as: :destroy_evaluations
  put 'evaluations/:film_api_id/:evaluation' => 'evaluations#update', as: :update_evaluations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord

  MAX_EVALUATION = 2

  belongs_to :user

  enum evaluation: [:dislike, :like]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :evaluations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include HTTParty

  base_uri 'https://swapi.co/api/films'

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def call_swapi(params)
    self.class.get(params)
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:username]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController

  before_action :sanitize_evaluation_params, only: [:create, :update]
  before_action :exceeded_amount_evaluation?, only: [:create]

  def index
    evaluations = Evaluation.group(:film_api_id)
                            .order('evaluation asc')
                            .count(:evaluation)

    @evaluations = []

    begin
      evaluations.each do |item|

        param = "/#{item.first}/?format=json"

        film = call_swapi(param)

        raise unless film.success?

        film['amount_votes'] = item.last

        @evaluations.push(film)
      end
      # foi realizado este modo reverse pois o comando DESC estava ordenando de forma errada
      @evaluations.reverse!
    rescue
      @evaluations.clear
      flash[:warning] = I18n.t(:'messages.error.call_api_error')
    end
  end

  def create
    evaluation = Evaluation.create(evaluations_params)

    if evaluation.save
      flash[:success] = I18n.t(:'messages.success.evaluation_success')
    else
      flash[:error] = I18n.t(:'messages.error.evaluation_fail')
    end

    redirect_user
  end

  def update
    params = evaluations_params

    evaluation = Evaluation.find_by(film_api_id: params[:film_api_id])

    if evaluation.update(evaluation: params[:evaluation])
      flash[:success] = I18n.t(:'messages.success.update_evaluation_succes')
    else
      flash[:error] = I18n.t(:'messages.error.update_evaluation_fail')
    end

    redirect_user
  end

  def destroy
    params = evaluations_params

    if Evaluation.destroy(params[:evaluation_id])
      flash[:success] = I18n.t(:'messages.success.update_evaluation_succes')
    else
      flash[:error] = I18n.t(:'messages.error.update_evaluation_fail')
    end

    redirect_user
  end

  private

  def sanitize_evaluation_params
    params[:evaluation] = params[:evaluation].to_i
    params[:user_id] = current_user.id
  end

  def evaluations_params
    params.permit(:film_api_id, :evaluation, :user_id, :evaluation_id)
  end

  def exceeded_amount_evaluation?
    evaluations_user = Evaluation.where(user_id: current_user.id)

    if evaluations_user.length >= Evaluation::MAX_EVALUATION
      flash[:warning] = I18n.t(:'messages.error.update_evaluation_exceeded')
      redirect_user
    end
  end

  def redirect_user
    redirect_to root_url
  end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :film_by_api, only: [:index]

  def index
    begin
      response = call_swapi('?format=json')

      raise unless response.success?

      @films = response['results']
    rescue
      flash[:warning] = I18n.t(:'messages.error.call_api_error')
    end
  end

  def show

  end

  private

  def film_by_api

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper

  def liked?(film_api_id)
    evaluation = define_evaluation(film_api_id)

    evaluation.like? ? 'text-success' : 'text-dark'
  end

  def disliked?(film_api_id)
    evaluation = define_evaluation(film_api_id)

    evaluation.dislike? ? 'text-danger' : 'text-dark'
  end

  def define_evaluation(film_api_id)
    Evaluation.find_by(film_api_id: film_api_id)
  end

  def find_evaluation(film_api_id)
    Evaluation.where(film_api_id: film_api_id, user_id: current_user.id)
  end

  def max_evaluation_num
    Evaluation::MAX_EVALUATION
  end
end

app/helpers/films_helper.rb
module FilmsHelper

  def date_format_year(date)
    date.to_time.strftime('%d/%m/%Y')
  end

  def format_api_id(url)
    url.gsub(/[^0-9]+/, '')
  end

  def find_evaluation_by_film_api_id(film_api_id)
    Evaluation.find_by(film_api_id: film_api_id, user_id: current_user.id)
  end
end

app/views/evaluations/_evaluations.html.erb
<% @evaluations.each do |evaluation| %>

  <tr class="px-2">
    <td style="width: 5%" class="text-left">
      <%= icon('fas', 'film', class: 'fa-2x py-3 text-info') %>
    </td>
    <td class="text-left">
      <%= evaluation['title'] %>
    </td>
    <td class="text-center">
      <%= evaluation['episode_id'] %>
    </td>
    <td class="text-center">
      <%= evaluation['director'] %>
    </td>
    <td class="text-center">
      <%= evaluation['amount_votes'] %>
    </td>
  </tr>
<% end %>

app/views/evaluations/index.html.erb
<div class="row">

  <div class="col-sm-12 mt-3 p-5 bg-white">

    <div class="pb-5">
      <h2>Filmes mais votados</h2>
    </div>

    <table class="table-responsive table-hover">
      <thead class="py-2">
        <tr>
          <th style="width: 10%" class="text-left"></th>
          <th class="w-25 text-left">Título</th>
          <th style="width: 15%" class="text-center">Episódio</th>
          <th style="width: 20%" class="text-center">Diretor</th>
          <th style="width: 5%" class="text-center">Votos</th>
        </tr>
      </thead>
      <% if @evaluations.length > 0 %>
        <tbody>
          <%= render 'evaluations' %>
        </tbody>
      <% else %>
        <div class="text-center mb-5">
          <h5 class="text-danger">Nenhuma avaliação encontrada</h5>
        </div>
      <% end %>
    </table>
  </div>

</div>

app/views/films/_films.html.erb
<% @films.each do |film| %>
  <tr class="px-2">
    <td class="text-left">
      <%= icon('fas', 'film', class: 'fa-2x py-3 text-info') %>
    </td>
    <td class="text-left">
      <%= film['title'] %>
    </td>
    <td class="text-center">
      <%= film['episode_id'] %>
    </td>
    <td class="text-center">
      <%= film['director'] %>
    </td>
    <td class="text-center">
      <%= date_format_year(film['release_date']) %>
    </td>

    <% if find_evaluation_by_film_api_id(format_api_id(film['url'])) %>

      <td class="text-center">
        <%= link_to update_evaluations_path(film_api_id: format_api_id(film['url']), evaluation: 1), method: :put do
          icon('fas', 'thumbs-up', class: "fa-2x py-3 #{liked?(format_api_id(film['url']))}")
        end %>
      </td>

      <td class="text-center">
        <%= link_to update_evaluations_path(film_api_id: format_api_id(film['url']), evaluation: 0), method: :put do
          icon('fas', 'thumbs-down', class: "fa-2x py-3 #{disliked?(format_api_id(film['url']))}")
        end %>
      </td>

    <% else %>

      <td class="text-center">
        <%= link_to create_evaluations_path(film_api_id: format_api_id(film['url']), evaluation: 1), method: :post do
          icon('fas', 'thumbs-up', class: 'fa-2x py-3 text-dark')
        end %>
      </td>

      <td class="text-center">
        <%= link_to create_evaluations_path(film_api_id: format_api_id(film['url']), evaluation: 0), method: :post do
          icon('fas', 'thumbs-down', class: 'fa-2x py-3 text-dark')
        end %>
      </td>

    <% end %>

    <td class="text-center">
      <% if find_evaluation(format_api_id(film['url'])).empty? %>

        <%= icon('fas', 'eraser', class: 'fa-2x py-3 text-info') %>

      <% else %>

        <%= link_to destroy_evaluations_path(evaluation_id: find_evaluation(format_api_id(film['url'])).ids), method: :delete do
          icon('fas', 'eraser', class: 'fa-2x py-3 text-info')
        end %>

      <% end %>
    </td>
  </tr>
<% end %>

app/views/films/index.html.erb
<div class="row">

  <div class="col-sm-12 mt-3 p-5 bg-white">

    <div class="pb-5">
      <h2>Listagem de Filmes</h2>
      <h6>
        <strong>Máximo de avaliações por usuário: </strong><%= max_evaluation_num %>
      </h6>
    </div>

    <table class="table-responsive table-hover">
      <thead class="py-2">
        <tr>
          <th style="width: 5%" class="text-left"></th>
          <th class="w-25 text-left">Título</th>
          <th style="width: 15%" class="text-center">Episódio</th>
          <th style="width: 20%" class="text-center">Diretor</th>
          <th style="width: 5%" class="text-center">Lançamento</th>
          <th style="width: 15%" class="text-center">Like</th>
          <th style="width: 10%" class="text-center">Dislike</th>
          <th style="width: 10%" class="text-center">Limpar</th>
        </tr>
      </thead>

      <% if !@films.nil? %>
        <tbody>
          <%= render 'films' %>
        </tbody>
      <% else %>
        <div class="text-center mb-5">
          <h5 class="text-danger">Nenhum filme encontrado</h5>
        </div>
      <% end %>
      </table>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <title>Biblioteca Star Wars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #f8f9fa;">

    <nav class="navbar navbar-expand-lg navbar-dark bg-light">

      <h2>
        Bem vindo, <strong><%= current_user.nil? ? 'Visitante' : current_user.username %></strong>
      </h2>

      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse d-flex flex-row-reverse">
        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger' do
            icon('fas', 'sign-out-alt')
          end %>&nbsp;&nbsp;&nbsp;

          <%= link_to edit_user_registration_path, class: 'btn btn-outline-dark' do
            icon('fas', 'user-edit')
          end%>&nbsp;&nbsp;

          <%= link_to 'Filmes Mais Votados', list_evaluations_url, class: 'btn btn-outline-info' %>&nbsp;&nbsp;

          <%= link_to 'Listagem de Filmes', root_url, class: 'btn btn-outline-success' %>
      <% else %>
          <%= link_to "Login", new_user_session_path, class: 'btn btn-outline-success'  %>&nbsp;&nbsp;&nbsp;
          <%= link_to "Registrar-se", new_user_registration_path, class: 'btn btn-outline-secondary'  %>
        <% end %>
      </div>
    </nav>

    <section class="container">

      <div class="d-flex justify-content-center">
        <% if notice || flash[:success] %>
          <p class="w-100 alert alert-success"><%= notice || flash[:success] %></p>
        <% end %>

        <% if alert || flash[:error] %>
          <p class="w-100 alert alert-danger"><%= alert || flash[:error] %></p>
        <% end %>

        <% if flash[:warning] %>
          <p class="w-100 alert alert-warning"><%= flash[:warning] %></p>
        <% end %>
      </div>

      <%= yield %>

    </section>

  </body>
</html>